# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.11.0"

pre_release = true

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.11/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
NVIDIA LTS: 580.95.05
NVIDIA Production: 570.195.03
NVIDIA Container Toolkit: 1.17.9
crun: 1.24
drbd: 9.2.15
ecr-credential-provider: 1.34.1
fuse3: 3.17.4
glibc: 2.42
gvisor: 20251020.0
hailort: 4.23.0
kata-containers: 3.21.0
lldpd: 1.0.20
cloudflared: 2025.10.0
nebula: 1.9.7
netbird: 0.59.8
newt: 1.5.2
nut-client: 2.8.4
qemu: 10.1.2
spin: 0.21.0
stargz-snapshotter: 0.18.0
tailscale: 1.90.2
talos-vmtoolsd: 1.4.0
youki: 0.5.6
zerotier: 1.16.0
zfs: 2.4.0-rc2
linux-firmware: 20251021
tenstorrent: 2.4.1
mdadm: 4.4

wolfi-base: sha256:815b27b8a70713c70404e44a718eddd52ea6f4a2bfad5f56455b52cd2789a9b2
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"
